#############################################################################
# Makefile for building: ex_05
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  ex_05.pro
# Template: subdirs
# Command: /home/lucien/Qt/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ex_05.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /home/lucien/Qt/5.2.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-general \
		sub-Qt_GL \
		sub-text \
		sub-Tests


sub-general-qmake_all:  FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile
	cd general/ && $(MAKE) -f Makefile qmake_all
sub-general: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-general-make_first: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-general-all: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-general-clean: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-general-distclean: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-general-install_subtargets: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-general-uninstall_subtargets: FORCE
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Qt_GL-qmake_all:  FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile
	cd Qt_GL/ && $(MAKE) -f Makefile qmake_all
sub-Qt_GL: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Qt_GL-make_first: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Qt_GL-all: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Qt_GL-clean: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Qt_GL-distclean: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Qt_GL-install_subtargets: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Qt_GL-uninstall_subtargets: FORCE
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-text-qmake_all:  FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile
	cd text/ && $(MAKE) -f Makefile qmake_all
sub-text: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-text-make_first: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-text-all: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-text-clean: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-text-distclean: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-text-install_subtargets: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-text-uninstall_subtargets: FORCE
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Tests-qmake_all:  FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile
	cd Tests/ && $(MAKE) -f Makefile qmake_all
sub-Tests: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Tests-make_first: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Tests-all: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Tests-clean: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Tests-distclean: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Tests-install_subtargets: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Tests-uninstall_subtargets: FORCE
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ex_05.pro ../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		ex_05.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ex_05.pro
../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf:
../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf:
../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf:
../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf:
ex_05.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ex_05.pro

qmake_all: sub-general-qmake_all sub-Qt_GL-qmake_all sub-text-qmake_all sub-Tests-qmake_all FORCE

make_first: sub-general-make_first sub-Qt_GL-make_first sub-text-make_first sub-Tests-make_first FORCE
all: sub-general-all sub-Qt_GL-all sub-text-all sub-Tests-all FORCE
clean: sub-general-clean sub-Qt_GL-clean sub-text-clean sub-Tests-clean FORCE
distclean: sub-general-distclean sub-Qt_GL-distclean sub-text-distclean sub-Tests-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-general-install_subtargets sub-Qt_GL-install_subtargets sub-text-install_subtargets sub-Tests-install_subtargets FORCE
uninstall_subtargets: sub-general-uninstall_subtargets sub-Qt_GL-uninstall_subtargets sub-text-uninstall_subtargets sub-Tests-uninstall_subtargets FORCE

sub-general-check:
	@test -d general/ || mkdir -p general/
	cd general/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/general/general.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Qt_GL-check:
	@test -d Qt_GL/ || mkdir -p Qt_GL/
	cd Qt_GL/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Qt_GL/Qt_GL.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-text-check:
	@test -d text/ || mkdir -p text/
	cd text/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/text/text.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Tests-check:
	@test -d Tests/ || mkdir -p Tests/
	cd Tests/ && ( test -e Makefile || $(QMAKE) /home/lucien/ProjetProgModel/Tests/Tests.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-general-check sub-Qt_GL-check sub-text-check sub-Tests-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

